class User:
    username = ''
    password = ''
    fullname = ''
    address = ''
    birthday = ''
    sex = ''
    Friend = ''
    receiver = ''
    content = ''
    block = ''
    editInfoFriend = ''
